version: '3'

services:    
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus    
    volumes:
      - ./prometheus/:/prometheus_data/
    command:
      - '--config.file=/prometheus_data/prometheus.yml'
    ports:
      - 9090:9090 
    networks:
      - app-network

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - app-network
    restart: always
  
  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    networks:
      - app-network
  # Alertteam  
  alertteam:
    image: idealista/prom2teams
    container_name: alertteam
    ports:
      - 8089:8089
    environment:
      - PROM2TEAMS_CONNECTOR="https://outlook.office.com/webhook/e6d3c9f5-1b43-4d16-80bd-993a13d59db9@8c3dad1d-b6bc-4f8b-939b-8263372eced6/IncomingWebhook/33124c1c83064a41b2bddc031fbe6e52/ffd415cf-de42-4a1f-a127-7c9a0d3c12af" 
    networks:
      - app-network
 
  # Inluxdb
  influxdb: 
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    ports:
      - 8086:8086

  # Chronograf
  chronograf: 
    image: chronograf:latest
    container_name: chronograf
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    ports:
      - 8888:8888

  # AlertManager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    tty: true
    volumes:
      - ./alertmanager/:/alertmanager_data/
    command:
      - '--config.file=/alertmanager_data/alertmanager.yml'
    networks:
      - app-network
    ports:
      - 9093:9093
 
  #Kapacitor  
  kapacitor: 
    image: kapacitor:latest
    container_name: kapacitor
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    ports:
      - 9092:9092
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
 
networks:
  app-network:
    driver: bridge
