alert: InstanceDown
expr: probe_success == 0
for: 1m
labels:
  severity: critical
annotations:
  description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for
    more than 1 minutes.'
  summary: Endpoint {{ $labels.instance }} down
