# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
         - 'alertmanager:9093'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
            - targets: ['10.21.12.120:9182','10.11.32.14:9182']


  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
     - targets:
       - https://www.robustperception.io/
       - https://hub.docker.com/v2/user/
       - https://unix.stackexchange.com
       - https://discoposse.com
       - https://hub.docker.com
       - http://ec2-52-53-177-18.us-west-1.compute.amazonaws.com
       - https://github.com/
       - https://blogpage.com/blogs       
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox:9115 # The blackbox exporter.
